import { StrictMode } from 'react'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../../../App'
import * as authApi from '../../auth/api/adminAccess'
import * as branchApi from '../api/branches'
import * as productApi from '../../products/api/products'

vi.mock('../../auth/api/adminAccess', () => ({ getAdminAccess: vi.fn(), signIn: vi.fn() }))
vi.mock('../api/branches', () => ({ listBranches: vi.fn(), createBranch: vi.fn(), setBranchStatus: vi.fn() }))
vi.mock('../../products/api/products', () => ({ listProducts: vi.fn(), createProduct: vi.fn(), updateProduct: vi.fn(), deactivateProduct: vi.fn() }))
const branch = { id: 'branch-1', name: 'Central', status: 'active' as const }
const deferred = <T,>() => {
  let resolve!: (value: T) => void
  const promise = new Promise<T>((done) => { resolve = done })
  return { promise, resolve }
}
describe('admin branch workspace', () => {
  afterEach(cleanup)
  beforeEach(() => {
    vi.resetAllMocks()
    vi.mocked(authApi.getAdminAccess).mockResolvedValue(true)
    vi.mocked(branchApi.listBranches).mockResolvedValue([])
    vi.mocked(productApi.listProducts).mockResolvedValue([])
  })
  it('shows one generic denial and never requests protected data', async () => {
    vi.mocked(authApi.getAdminAccess).mockResolvedValue(false)
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'Access unavailable' })).toBeInTheDocument()
    expect(screen.queryByText('inactive')).not.toBeInTheDocument(); expect(branchApi.listBranches).not.toHaveBeenCalled()
  })
  it('focuses an access error and retries the server check', async () => {
    vi.mocked(authApi.getAdminAccess).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(false)
    render(<App />)
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Try again' }))
    expect(await screen.findByRole('heading', { name: 'Access unavailable' })).toBeInTheDocument()
  })
  it('moves from accessible loading to the empty workspace', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    render(<App />)
    expect(await screen.findByText('Loading branches…')).toHaveAttribute('role', 'status')
    load.resolve([])
    expect(await screen.findByText('No branches yet.')).toBeInTheDocument()
  })
  it('shows a successful create while an older list is pending', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    vi.mocked(branchApi.createBranch).mockResolvedValue(branch)
    render(<App />)
    await screen.findByText('Loading branches…')
    fireEvent.change(screen.getByLabelText('Branch name'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Create branch' }))
    expect(await screen.findByText('Central')).toBeInTheDocument()
    expect(screen.queryByText('Loading branches…')).not.toBeInTheDocument()
    load.resolve([])
    await waitFor(() => expect(screen.getByText('Central')).toBeInTheDocument())
  })
  it('serializes commands and keeps the confirmed result visible', async () => {
    const status = deferred<branchApi.Branch>()
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus).mockReturnValue(status.promise)
    render(<App />)
    fireEvent.click(await screen.findByRole('button', { name: 'Suspend Central' }))
    for (const name of ['Refresh branches', 'Create branch', 'Suspend Central'])
      expect(screen.getByRole('button', { name })).toBeDisabled()
    fireEvent.submit(screen.getByRole('form', { name: 'Create branch' }))
    expect(branchApi.createBranch).not.toHaveBeenCalled()
    status.resolve({ ...branch, status: 'suspended' })
    expect(await screen.findByText('Suspended')).toBeInTheDocument()
  })
  it('keeps the newest admin access response', async () => {
    const older = deferred<boolean>()
    const newer = deferred<boolean>()
    vi.mocked(authApi.getAdminAccess)
      .mockReturnValueOnce(older.promise)
      .mockReturnValueOnce(newer.promise)
    render(<StrictMode><App /></StrictMode>)
    newer.resolve(true)
    expect(await screen.findByRole('heading', { name: 'Branches' })).toBeInTheDocument()
    older.resolve(false)
    await waitFor(() => expect(screen.queryByRole('heading', { name: 'Access unavailable' })).not.toBeInTheDocument())
  })
  it('recovers from a branch loading error', async () => {
    vi.mocked(branchApi.listBranches)
      .mockRejectedValueOnce(new Error('offline'))
      .mockResolvedValueOnce([])
    render(<App />)
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveTextContent('Branches could not be loaded')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Try again' }))
    expect(await screen.findByText('No branches yet.')).toBeInTheDocument()
  })
  it('retries create with the same request ID', async () => {
    vi.mocked(branchApi.createBranch)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce(branch)
    render(<App />)
    await screen.findByText('No branches yet.')
    fireEvent.change(screen.getByLabelText('Branch name'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Create branch' }))
    await screen.findByText('The branch was not created.')
    fireEvent.click(screen.getByRole('button', { name: 'Retry create' }))
    expect(await screen.findByText('Central')).toBeInTheDocument()
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).toBe(calls[1][1])
  })
  it('uses a new request ID for a divergent create intent', async () => {
    vi.mocked(branchApi.createBranch).mockRejectedValue(new Error('conflict'))
    render(<App />)
    await screen.findByText('No branches yet.')
    const input = screen.getByLabelText('Branch name')
    fireEvent.change(input, { target: { value: 'Central' } }); fireEvent.submit(screen.getByRole('form', { name: 'Create branch' }))
    await screen.findByText('The branch was not created.')
    fireEvent.change(input, { target: { value: 'North' } }); fireEvent.submit(screen.getByRole('form', { name: 'Create branch' }))
    await waitFor(() => expect(branchApi.createBranch).toHaveBeenCalledTimes(2))
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).not.toBe(calls[1][1])
  })
  it('retries a status change with the same request ID', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce({ ...branch, status: 'suspended' })
    render(<App />)
    fireEvent.click(await screen.findByRole('button', { name: 'Suspend Central' }))
    await screen.findByText('The branch status was not changed.')
    fireEvent.click(screen.getByRole('button', { name: 'Retry status change' }))
    expect(await screen.findByText('Suspended')).toBeInTheDocument()
    const calls = vi.mocked(branchApi.setBranchStatus).mock.calls
    expect(calls[0][2]).toBe(calls[1][2])
  })
  it('ignores stale branch responses', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValueOnce([branch])
    render(<App />)
    await screen.findByText('Central')
    const older = deferred<branchApi.Branch[]>()
    const newer = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches)
      .mockReturnValueOnce(older.promise)
      .mockReturnValueOnce(newer.promise)
    fireEvent.click(screen.getByRole('button', { name: 'Refresh branches' }))
    fireEvent.click(screen.getByRole('button', { name: 'Refresh branches' }))
    newer.resolve([{ ...branch, id: 'new', name: 'North' }])
    expect(await screen.findByText('North')).toBeInTheDocument()
    older.resolve([{ ...branch, id: 'old', name: 'Stale' }])
    await waitFor(() => expect(screen.queryByText('Stale')).not.toBeInTheDocument())
  })
})
