import { StrictMode } from 'react'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../../../App'
import * as authApi from '../../auth/api/adminAccess'
import * as branchApi from '../api/branches'
import * as employeeApi from '../api/employees'
import * as productApi from '../../products/api/products'
import * as salesApi from '../../sales/api/sales'

vi.mock('../../auth/api/adminAccess', () => ({ getAccessContext: vi.fn(), signIn: vi.fn() }))
vi.mock('../api/branches', () => ({ listBranches: vi.fn(), createBranch: vi.fn(), renameBranch: vi.fn(), setBranchStatus: vi.fn() }))
vi.mock('../api/employees', () => ({ listEmployees: vi.fn(), createEmployee: vi.fn(), setEmployeeStatus: vi.fn(), updateEmployee: vi.fn(), setEmployeePassword: vi.fn() }))
vi.mock('../../products/api/products', () => ({ listProducts: vi.fn(), createProduct: vi.fn(), updateProduct: vi.fn(), deactivateProduct: vi.fn(), MAX_PRODUCT_TAG_LENGTH: 48, MAX_PRODUCT_TAGS: 20, PRODUCT_IMAGE_MAX_BYTES: 5 * 1024 * 1024, PRODUCT_IMAGE_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp'], normalizeProductTags: (value: unknown) => Array.isArray(value) ? value.map((tag) => String(tag).trim()).filter(Boolean) : [] }))
vi.mock('../../sales/api/sales', () => ({ SALES_CHANNELS: ['pos', 'wholesale', 'event'], REPORT_TIMEZONE: 'America/Mexico_City', recordSale: vi.fn(), getSalesByChannel: vi.fn(), getReportDashboardSnapshot: vi.fn() }))
const branch = { id: 'branch-1', name: 'Central', status: 'active' as const }
const employee = { userId: 'employee-1', username: 'ana.cajera', displayName: 'Ana Cajera', branchId: 'branch-1', branchName: 'Central', status: 'active' as const, branchStatus: 'active' as const }
const deferred = <T,>() => {
  let resolve!: (value: T) => void
  const promise = new Promise<T>((done) => { resolve = done })
  return { promise, resolve }
}
const openBranches = async () => {
  fireEvent.click(await screen.findByRole('button', { name: 'Abrir menú de navegación' }))
  fireEvent.click(within(screen.getByRole('dialog', { name: 'Navegación de módulos' })).getByRole('button', { name: /Sucursales/ }))
}
const openEmployees = async () => {
  await openBranches()
  fireEvent.click(await screen.findByRole('tab', { name: 'Empleados' }))
}
describe('admin branch workspace', () => {
  afterEach(cleanup)
  beforeEach(() => {
    vi.resetAllMocks()
    window.history.replaceState(null, '', '/admin')
    vi.mocked(authApi.getAccessContext).mockResolvedValue({ role: 'admin', userId: 'admin-1', displayName: null, capabilities: ['branches.manage'], branch: null })
    vi.mocked(branchApi.listBranches).mockResolvedValue([])
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([])
    vi.mocked(productApi.listProducts).mockResolvedValue([])
    vi.mocked(salesApi.getSalesByChannel).mockResolvedValue([])
    let requestSequence = 0
    vi.stubGlobal('crypto', { randomUUID: vi.fn(() => `request-${++requestSequence}`) })
  })
  it('shows one generic denial and never requests protected data', async () => {
    vi.mocked(authApi.getAccessContext).mockResolvedValue(null)
    render(<App />)
    expect(await screen.findByRole('region', { name: 'Acceso administrativo' })).toBeInTheDocument()
    expect(screen.getByRole('link', { name: /Ir a iniciar sesión/ })).toHaveAttribute('href', '/app')
    expect(screen.queryByText('inactive')).not.toBeInTheDocument(); expect(branchApi.listBranches).not.toHaveBeenCalled()
  })
  it('focuses an access error and retries the server check', async () => {
    vi.mocked(authApi.getAccessContext).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(null)
    render(<App />)
    const alert = await screen.findByRole('alert')
     expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByRole('region', { name: 'Acceso administrativo' })).toBeInTheDocument()
  })
  it('moves from accessible loading to the empty workspace', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    render(<App />)
    await openBranches()
    expect(await screen.findByText('Cargando sucursales…')).toHaveAttribute('role', 'status')
    load.resolve([])
    expect(await screen.findByText('Aún no hay sucursales.')).toBeInTheDocument()
    expect(screen.getByRole('region', { name: 'Módulo Sucursales' })).toHaveClass('flex', 'min-h-0', 'flex-1', 'flex-col', 'overflow-hidden')
    expect(screen.getByRole('region', { name: 'Módulo Sucursales' })).toHaveClass('ops-workspace-frame', 'min-w-0')
    expect(screen.getByRole('tabpanel', { name: 'Sucursales' })).toHaveClass('flex', 'min-h-0', 'flex-1', 'flex-col', 'overflow-hidden')
  })
  it('switches between the two branch tabs and renders only the active panel', async () => {
    render(<App />)
    await openBranches()

    expect(screen.getAllByRole('tab')).toHaveLength(2)
    expect(screen.getByRole('tab', { name: 'Sucursales' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByRole('tabpanel', { name: 'Sucursales' })).toBeInTheDocument()
    expect(screen.queryByRole('tabpanel', { name: 'Empleados' })).not.toBeInTheDocument()

    const employeesTab = screen.getByRole('tab', { name: 'Empleados' })
    fireEvent.click(employeesTab)
    expect(screen.getByRole('tab', { name: 'Empleados' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByRole('tabpanel', { name: 'Empleados' })).toBeInTheDocument()
    expect(screen.queryByRole('tabpanel', { name: 'Sucursales' })).not.toBeInTheDocument()

    fireEvent.keyDown(employeesTab, { key: 'ArrowLeft' })
    expect(screen.getByRole('tab', { name: 'Sucursales' })).toHaveAttribute('aria-selected', 'true')
  })
  it('keeps the sucursales heading free of the removed administration eyebrow', async () => {
    render(<App />)
    await openBranches()

    expect(screen.getByRole('tab', { name: 'Sucursales' })).toBeInTheDocument()
    expect(screen.queryByText('Administración', { selector: 'p' })).not.toBeInTheDocument()
  })
  it('uses a square plus-only button beside the branch name field', async () => {
    render(<App />)
    await openBranches()

    const button = screen.getByRole('button', { name: 'Crear sucursal' })
    expect(button).toHaveClass('h-11', 'w-11', 'min-h-11', 'min-w-11', 'shrink-0')
    expect(button).not.toHaveTextContent('Crear sucursal')
    expect(button.querySelector('[data-icon="plus"]')).toBeInTheDocument()
  })
  it('creates an employee from the modal and resets its form state', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(employeeApi.createEmployee).mockResolvedValue(employee)
    render(<App />)
    await openEmployees()
    expect(await screen.findByText('Aún no hay empleados asignados.')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'Crear empleado' }))
    const dialog = await screen.findByRole('dialog', { name: 'Crear empleado' })
    const form = within(dialog).getByRole('form', { name: 'Crear empleado' })
    expect(form).toHaveAttribute('id', 'create-employee-form')
    expect(within(dialog).getByRole('button', { name: 'Crear empleado' })).toHaveAttribute('form', 'create-employee-form')

    fireEvent.change(within(dialog).getByLabelText('Nombre para mostrar'), { target: { value: employee.displayName } })
    fireEvent.change(within(dialog).getByLabelText('Usuario'), { target: { value: employee.username } })
    fireEvent.change(within(dialog).getByLabelText('Contraseña'), { target: { value: 'secure-pass' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Sucursal asignada' }))
    fireEvent.click(screen.getByRole('option', { name: 'Central' }))
    fireEvent.click(within(dialog).getByRole('button', { name: 'Mostrar contraseña' }))
    fireEvent.click(within(dialog).getByRole('button', { name: 'Crear empleado' }))

    expect(await screen.findByRole('heading', { name: 'Ana Cajera' })).toBeInTheDocument()
    expect(employeeApi.createEmployee).toHaveBeenCalledWith({ displayName: 'Ana Cajera', username: 'ana.cajera', password: 'secure-pass', branchId: 'branch-1' })
    expect(screen.queryByRole('dialog', { name: 'Crear empleado' })).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'Crear empleado' }))
    const reopenedDialog = await screen.findByRole('dialog', { name: 'Crear empleado' })
    expect(within(reopenedDialog).getByLabelText('Nombre para mostrar')).toHaveValue('')
    expect(within(reopenedDialog).getByLabelText('Usuario')).toHaveValue('')
    expect(within(reopenedDialog).getByLabelText('Contraseña')).toHaveValue('')
    expect(within(reopenedDialog).getByLabelText('Contraseña')).toHaveAttribute('type', 'password')
    expect(within(reopenedDialog).getByRole('button', { name: 'Mostrar contraseña' })).toHaveAttribute('aria-pressed', 'false')
    expect(within(reopenedDialog).getByRole('button', { name: 'Sucursal asignada' })).toHaveTextContent('Selecciona una sucursal activa')
  })
  it('searches employees by display name, username, and branch case-insensitively', async () => {
    const north = { id: 'branch-2', name: 'Norte', status: 'active' as const }
    const secondEmployee = { userId: 'employee-2', username: 'luis.norte', displayName: 'Luis Norte', branchId: 'branch-2', branchName: 'Norte', status: 'active' as const, branchStatus: 'active' as const }
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch, north])
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee, secondEmployee])
    render(<App />)
    await openEmployees()
    expect(await screen.findByRole('heading', { name: 'Ana Cajera' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Luis Norte' })).toBeInTheDocument()

    const search = screen.getByRole('searchbox', { name: 'Buscar empleados' })
    fireEvent.change(search, { target: { value: 'ANA CAJERA' } })
    expect(screen.getByRole('heading', { name: 'Ana Cajera' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Luis Norte' })).not.toBeInTheDocument()
    fireEvent.change(search, { target: { value: 'LUIS.NORTE' } })
    expect(screen.getByRole('heading', { name: 'Luis Norte' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Ana Cajera' })).not.toBeInTheDocument()
    fireEvent.change(search, { target: { value: 'nOrTe' } })
    expect(screen.getByRole('heading', { name: 'Luis Norte' })).toBeInTheDocument()
  })
  it('keeps the employee search and create action in the shared branch toolbar shell', async () => {
    render(<App />)
    await openEmployees()

    const search = screen.getByRole('searchbox', { name: 'Buscar empleados' })
    const createButton = screen.getByRole('button', { name: 'Crear empleado' })
    const toolbar = search.closest('div')?.parentElement
    expect(toolbar).toHaveClass('flex', 'min-w-0', 'items-end', 'rounded-2xl', 'border', 'bg-slate-950', 'p-3', 'sm:p-4')
    expect(toolbar).toContainElement(createButton)
  })
  it('shows a dedicated neutral empty state when employee search has no matches', async () => {
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    render(<App />)
    await openEmployees()
    expect(await screen.findByRole('heading', { name: 'Ana Cajera' })).toBeInTheDocument()

    fireEvent.change(screen.getByRole('searchbox', { name: 'Buscar empleados' }), { target: { value: 'inexistente' } })
    expect(await screen.findByText('No hay empleados que coincidan con la búsqueda.')).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Ana Cajera' })).not.toBeInTheDocument()
    expect(screen.queryByText('Aún no hay empleados asignados.')).not.toBeInTheDocument()
  })
  it('orders edit and password actions before the employee status action', async () => {
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    render(<App />)
    await openEmployees()
    await screen.findByRole('heading', { name: 'Ana Cajera' })

    const row = screen.getByRole('heading', { name: 'Ana Cajera' }).closest('li')
    expect(row).not.toBeNull()
    expect(within(row!).getAllByRole('button').map((button) => button.getAttribute('aria-label'))).toEqual([
      'Editar usuario Ana Cajera',
      'Cambiar contraseña de Ana Cajera',
      'Suspender Ana Cajera',
    ])
  })
  it('edits an employee and merges the returned row', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch, { id: 'branch-2', name: 'Norte', status: 'active' }])
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    const updatedEmployee = { ...employee, username: 'ana.nueva', displayName: 'Ana Nueva', branchId: 'branch-2', branchName: 'Norte' }
    vi.mocked(employeeApi.updateEmployee).mockResolvedValue(updatedEmployee)
    render(<App />)
    await openEmployees()
    await screen.findByRole('heading', { name: 'Ana Cajera' })

    fireEvent.click(screen.getByRole('button', { name: 'Editar usuario Ana Cajera' }))
    const dialog = await screen.findByRole('dialog', { name: 'Editar usuario' })
    const saveButton = within(dialog).getByRole('button', { name: 'Guardar cambios' })
    expect(saveButton.closest('header')).toBe(dialog.querySelector('[data-modal-header]'))
    expect(saveButton).toHaveAttribute('form', 'edit-employee-form')
    expect(within(dialog).queryByRole('button', { name: 'Cancelar' })).not.toBeInTheDocument()
    fireEvent.change(within(dialog).getByLabelText('Nombre para mostrar'), { target: { value: 'Ana Nueva' } })
    fireEvent.change(within(dialog).getByLabelText('Usuario'), { target: { value: 'ana.nueva' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Sucursal activa' }))
    fireEvent.click(screen.getByRole('option', { name: 'Norte' }))
    fireEvent.click(saveButton)

    expect(await screen.findByRole('heading', { name: 'Ana Nueva' })).toBeInTheDocument()
    expect(employeeApi.updateEmployee).toHaveBeenCalledWith({ userId: 'employee-1', username: 'ana.nueva', displayName: 'Ana Nueva', branchId: 'branch-2' })
    expect(screen.queryByRole('dialog', { name: 'Editar usuario' })).not.toBeInTheDocument()
  })
  it('validates and saves a password without retaining it in an error state', async () => {
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    vi.mocked(employeeApi.setEmployeePassword).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(true)
    render(<App />)
    await openEmployees()
    await screen.findByRole('heading', { name: 'Ana Cajera' })

    fireEvent.click(screen.getByRole('button', { name: 'Cambiar contraseña de Ana Cajera' }))
    const dialog = await screen.findByRole('dialog', { name: 'Cambiar contraseña' })
    const saveButton = within(dialog).getByRole('button', { name: 'Guardar contraseña' })
    expect(saveButton.closest('header')).toBe(dialog.querySelector('[data-modal-header]'))
    expect(saveButton).toHaveAttribute('form', 'password-employee-form')
    expect(within(dialog).queryByRole('button', { name: 'Cancelar' })).not.toBeInTheDocument()
    fireEvent.change(within(dialog).getByLabelText('Nueva contraseña'), { target: { value: 'secure-pass' } })
    fireEvent.change(within(dialog).getByLabelText('Confirmar contraseña'), { target: { value: 'different-pass' } })
    fireEvent.click(saveButton)
    expect(await within(dialog).findByRole('alert')).toHaveTextContent('Las contraseñas no coinciden.')
    expect(employeeApi.setEmployeePassword).not.toHaveBeenCalled()

    fireEvent.change(within(dialog).getByLabelText('Confirmar contraseña'), { target: { value: 'secure-pass' } })
    fireEvent.click(saveButton)
    expect(await within(dialog).findByText(/No se pudo cambiar la contraseña\./)).toBeInTheDocument()
    expect(within(dialog).getByLabelText('Nueva contraseña')).toHaveValue('')
    expect(within(dialog).getByLabelText('Confirmar contraseña')).toHaveValue('')
    expect(within(dialog).queryByRole('button', { name: /Reintentar/ })).not.toBeInTheDocument()

    fireEvent.change(within(dialog).getByLabelText('Nueva contraseña'), { target: { value: 'secure-pass-2' } })
    fireEvent.change(within(dialog).getByLabelText('Confirmar contraseña'), { target: { value: 'secure-pass-2' } })
    fireEvent.click(saveButton)
    expect(await screen.findByText('Contraseña actualizada.')).toBeInTheDocument()
    expect(employeeApi.setEmployeePassword).toHaveBeenNthCalledWith(2, { userId: 'employee-1', password: 'secure-pass-2' })
  })
  it('toggles employee password visibility with accessible state and icons', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    render(<App />)
    await openEmployees()
    await screen.findByText('Aún no hay empleados asignados.')

    fireEvent.click(screen.getByRole('button', { name: 'Crear empleado' }))
    const dialog = await screen.findByRole('dialog', { name: 'Crear empleado' })
    const password = within(dialog).getByLabelText('Contraseña')
    const showButton = within(dialog).getByRole('button', { name: 'Mostrar contraseña' })
    expect(password).toHaveAttribute('type', 'password')
    expect(password).toHaveAttribute('autocomplete', 'new-password')
    expect(showButton).toHaveAttribute('title', 'Mostrar contraseña')
    expect(showButton).toHaveAttribute('aria-pressed', 'false')
    expect(showButton).toHaveAttribute('type', 'button')
    expect(showButton).toHaveClass('ops-icon-button')
    expect(showButton.querySelector('[data-icon="eye"]')).toBeInTheDocument()

    fireEvent.click(showButton)

    const hideButton = within(dialog).getByRole('button', { name: 'Ocultar contraseña' })
    expect(password).toHaveAttribute('type', 'text')
    expect(hideButton).toHaveAttribute('title', 'Ocultar contraseña')
    expect(hideButton).toHaveAttribute('aria-pressed', 'true')
    expect(hideButton.querySelector('[data-icon="eye-off"]')).toBeInTheDocument()
  })
  it('keeps a create failure focused inside the modal without retaining the password', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(employeeApi.createEmployee).mockRejectedValue({ code: 'EMPLOYEE_USERNAME_TAKEN', status: 409, retryable: false })
    render(<App />)
    await openEmployees()
    await screen.findByText('Aún no hay empleados asignados.')

    fireEvent.click(screen.getByRole('button', { name: 'Crear empleado' }))
    const dialog = await screen.findByRole('dialog', { name: 'Crear empleado' })
    fireEvent.change(within(dialog).getByLabelText('Nombre para mostrar'), { target: { value: employee.displayName } })
    fireEvent.change(within(dialog).getByLabelText('Usuario'), { target: { value: employee.username } })
    fireEvent.change(within(dialog).getByLabelText('Contraseña'), { target: { value: 'secure-pass' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Sucursal asignada' }))
    fireEvent.click(screen.getByRole('option', { name: 'Central' }))
    fireEvent.click(within(dialog).getByRole('button', { name: 'Crear empleado' }))

    const alert = await within(dialog).findByRole('alert')
    expect(alert).toHaveTextContent('Ese usuario ya existe. Elige otro usuario para continuar.')
    await waitFor(() => expect(alert).toHaveFocus())
    expect(within(dialog).queryByRole('button', { name: 'Cancelar' })).not.toBeInTheDocument()
    expect(within(dialog).queryByRole('button', { name: /Reintentar/ })).not.toBeInTheDocument()
    expect(within(dialog).getByLabelText('Contraseña')).toHaveValue('')
    expect(within(dialog).getByLabelText('Contraseña')).toHaveAttribute('type', 'password')
  })
  it('recovers from an employee loading error', async () => {
    vi.mocked(employeeApi.listEmployees).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce([employee])
    render(<App />)
    await openEmployees()
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveTextContent('No se pudieron cargar los empleados')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar carga de empleados' }))
    expect(await screen.findByRole('heading', { name: 'Ana Cajera' })).toBeInTheDocument()
  })
  it('retries an employee status change without losing the employee context', async () => {
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    vi.mocked(employeeApi.setEmployeeStatus)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce({ ...employee, status: 'suspended' })
    render(<App />)
    await openEmployees()
    await screen.findByRole('heading', { name: 'Ana Cajera' })
    fireEvent.click(screen.getByRole('button', { name: 'Suspender Ana Cajera' }))
    await screen.findByText('No se pudo cambiar el estado del empleado.')
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar cambio de estado' }))
    expect(await screen.findByText('Suspendido · Sucursal activa')).toBeInTheDocument()
    expect(employeeApi.setEmployeeStatus).toHaveBeenCalledWith('employee-1', 'suspended')
  })
  it('shows a successful create while an older list is pending', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    vi.mocked(branchApi.createBranch).mockResolvedValue(branch)
    render(<App />)
    await openBranches()
    await screen.findByText('Cargando sucursales…')
    fireEvent.change(screen.getByLabelText('Nombre de la sucursal'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    expect(await screen.findByRole('heading', { name: 'Central' })).toBeInTheDocument()
    expect(screen.queryByText('Cargando sucursales…')).not.toBeInTheDocument()
    load.resolve([])
    await waitFor(() => expect(screen.getByRole('heading', { name: 'Central' })).toBeInTheDocument())
  })
  it('serializes branch removal and keeps the confirmed suspended result visible', async () => {
    const status = deferred<branchApi.Branch>()
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus).mockReturnValue(status.promise)
    render(<App />)
    await openBranches()
    expect(screen.getByRole('button', { name: 'Actualizar sucursales' }).querySelector('[data-icon="refresh"]')).toBeInTheDocument()
    fireEvent.click(await screen.findByRole('button', { name: 'Eliminar sucursal Central' }))
    const removalDialog = await screen.findByRole('dialog', { name: 'Eliminar sucursal' })
    fireEvent.click(within(removalDialog).getByRole('button', { name: 'Confirmar eliminación' }))
    for (const name of ['Actualizar sucursales', 'Crear sucursal', 'Editar sucursal Central'])
      expect(screen.getByRole('button', { name })).toBeDisabled()
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    expect(branchApi.createBranch).not.toHaveBeenCalled()
    status.resolve({ ...branch, status: 'suspended' })
    expect(await screen.findByText('Suspendida')).toBeInTheDocument()
  })
  it('keeps admin access in StrictMode after deduplicating startup checks', async () => {
    vi.mocked(authApi.getAccessContext).mockResolvedValue({ role: 'admin', userId: 'admin-1', displayName: null, capabilities: [], branch: null })
    render(<StrictMode><App /></StrictMode>)
    await openBranches()
    expect(await screen.findByRole('tab', { name: 'Sucursales' })).toBeInTheDocument()
  })
  it('recovers from a branch loading error', async () => {
    vi.mocked(branchApi.listBranches)
      .mockRejectedValueOnce(new Error('offline'))
      .mockResolvedValueOnce([])
    render(<App />)
    await openBranches()
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveTextContent('No se pudieron cargar las sucursales')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByText('Aún no hay sucursales.')).toBeInTheDocument()
  })
  it('retries create with the same request ID', async () => {
    vi.mocked(branchApi.createBranch)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce(branch)
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')
    fireEvent.change(screen.getByLabelText('Nombre de la sucursal'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await screen.findByText('No se pudo crear la sucursal.')
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar creación' }))
    expect(await screen.findByRole('heading', { name: 'Central' })).toBeInTheDocument()
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).toBe(calls[1][1])
  })
  it('retains the branch draft while a failed create can be retried', async () => {
    vi.mocked(branchApi.createBranch).mockRejectedValueOnce(new Error('timeout'))
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')
    const input = screen.getByLabelText('Nombre de la sucursal')
    fireEvent.change(input, { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))

    await screen.findByText('No se pudo crear la sucursal.')
    expect(input).toHaveValue('Central')
    expect(screen.getByRole('button', { name: 'Reintentar creación' })).toBeEnabled()
  })
  it('preserves a newer draft when an earlier create succeeds', async () => {
    const pendingCreate = deferred<branchApi.Branch>()
    vi.mocked(branchApi.createBranch).mockReturnValue(pendingCreate.promise)
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')

    const input = screen.getByLabelText('Nombre de la sucursal')
    fireEvent.change(input, { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    fireEvent.change(input, { target: { value: 'Norte' } })
    pendingCreate.resolve(branch)

    expect(await screen.findByRole('heading', { name: 'Central' })).toBeInTheDocument()
    await waitFor(() => expect(input).toHaveValue('Norte'))
  })
  it('uses a new request ID for a divergent create intent', async () => {
    vi.mocked(branchApi.createBranch).mockRejectedValue(new Error('conflict'))
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')
    const input = screen.getByLabelText('Nombre de la sucursal')
    fireEvent.change(input, { target: { value: 'Central' } }); fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await screen.findByText('No se pudo crear la sucursal.')
    fireEvent.change(input, { target: { value: 'North' } }); fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await waitFor(() => expect(branchApi.createBranch).toHaveBeenCalledTimes(2))
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).not.toBe(calls[1][1])
  })
  it('retries a branch removal with the same request ID', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce({ ...branch, status: 'suspended' })
    render(<App />)
    await openBranches()
    fireEvent.click(await screen.findByRole('button', { name: 'Eliminar sucursal Central' }))
    const dialog = await screen.findByRole('dialog', { name: 'Eliminar sucursal' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar eliminación' }))
    await within(dialog).findByText(/No se pudo confirmar la eliminación/)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar eliminación' }))
    expect(await screen.findByText('Suspendida')).toBeInTheDocument()
    const calls = vi.mocked(branchApi.setBranchStatus).mock.calls
    expect(calls[0][2]).toBe(calls[1][2])
  })
  it('renames a branch through the edit dialog', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.renameBranch).mockResolvedValue({ ...branch, name: 'Sucursal Norte' })
    render(<App />)
    await openBranches()
    await screen.findByRole('heading', { name: 'Central' })

    fireEvent.click(screen.getByRole('button', { name: 'Editar sucursal Central' }))
    const dialog = await screen.findByRole('dialog', { name: 'Editar sucursal' })
    fireEvent.change(within(dialog).getByLabelText('Nombre de la sucursal'), { target: { value: 'Sucursal Norte' } })
    fireEvent.submit(within(dialog).getByRole('form', { name: 'Editar sucursal' }))

    expect(await screen.findByRole('heading', { name: 'Sucursal Norte' })).toBeInTheDocument()
    expect(branchApi.renameBranch).toHaveBeenCalledWith('branch-1', 'Sucursal Norte', expect.any(String))
    expect(screen.queryByRole('dialog', { name: 'Editar sucursal' })).not.toBeInTheDocument()
  })
  it('edits and retries a branch when crypto.randomUUID is unavailable', async () => {
    vi.stubGlobal('crypto', {
      getRandomValues: vi.fn((bytes: Uint8Array) => {
        bytes.fill(0)
        return bytes
      }),
    })
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.renameBranch)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce({ ...branch, name: 'Sucursal Norte' })
    render(<App />)
    await openBranches()
    await screen.findByRole('heading', { name: 'Central' })

    fireEvent.click(screen.getByRole('button', { name: 'Editar sucursal Central' }))
    const dialog = await screen.findByRole('dialog', { name: 'Editar sucursal' })
    fireEvent.change(within(dialog).getByLabelText('Nombre de la sucursal'), { target: { value: 'Sucursal Norte' } })
    const form = within(dialog).getByRole('form', { name: 'Editar sucursal' })
    fireEvent.submit(form)
    await within(dialog).findByText(/No se pudo actualizar el nombre/)

    fireEvent.submit(form)
    expect(await screen.findByRole('heading', { name: 'Sucursal Norte' })).toBeInTheDocument()
    const calls = vi.mocked(branchApi.renameBranch).mock.calls
    expect(calls[0][2]).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)
    expect(calls[1][2]).toBe(calls[0][2])
  })
  it('soft-deletes a branch by suspending it and keeps employee links recoverable', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(employeeApi.listEmployees).mockResolvedValue([employee])
    vi.mocked(branchApi.setBranchStatus)
      .mockResolvedValueOnce({ ...branch, status: 'suspended' })
      .mockResolvedValueOnce(branch)
    render(<App />)
    await openBranches()
    await screen.findByRole('heading', { name: 'Central' })
    fireEvent.click(screen.getByRole('tab', { name: 'Empleados' }))
    await screen.findByRole('heading', { name: 'Ana Cajera' })
    fireEvent.click(screen.getByRole('tab', { name: 'Sucursales' }))

    fireEvent.click(screen.getByRole('button', { name: 'Eliminar sucursal Central' }))
    const dialog = await screen.findByRole('dialog', { name: 'Eliminar sucursal' })
    expect(within(dialog).getByText(/quedará suspendida para conservar su historial, ventas y empleados asociados/i)).toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar eliminación' }))

    expect(await screen.findByText('Suspendida')).toBeInTheDocument()
    expect(branchApi.setBranchStatus).toHaveBeenCalledWith('branch-1', 'suspended', expect.any(String))
    fireEvent.click(screen.getByRole('tab', { name: 'Empleados' }))
    expect(await screen.findByText('Activo · Sucursal suspendida')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('tab', { name: 'Sucursales' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Reactivar Central' }))
    expect(await screen.findByText('Activa')).toBeInTheDocument()
    expect(branchApi.setBranchStatus).toHaveBeenLastCalledWith('branch-1', 'active', expect.any(String))
  })
  it('ignores stale branch responses', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValueOnce([branch])
    render(<App />)
    await openBranches()
    await screen.findByRole('heading', { name: 'Central' })
    const older = deferred<branchApi.Branch[]>()
    const newer = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches)
      .mockReturnValueOnce(older.promise)
      .mockReturnValueOnce(newer.promise)
    fireEvent.click(screen.getByRole('button', { name: 'Actualizar sucursales' }))
    fireEvent.click(screen.getByRole('button', { name: 'Actualizar sucursales' }))
    newer.resolve([{ ...branch, id: 'new', name: 'North' }])
    expect(await screen.findByRole('heading', { name: 'North' })).toBeInTheDocument()
    older.resolve([{ ...branch, id: 'old', name: 'Stale' }])
    await waitFor(() => expect(screen.queryByText('Stale')).not.toBeInTheDocument())
  })
})
