import { StrictMode } from 'react'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../../../App'
import * as authApi from '../../auth/api/adminAccess'
import * as branchApi from '../api/branches'
import * as productApi from '../../products/api/products'
import * as salesApi from '../../sales/api/sales'

vi.mock('../../auth/api/adminAccess', () => ({ getAdminAccess: vi.fn(), signIn: vi.fn() }))
vi.mock('../api/branches', () => ({ listBranches: vi.fn(), createBranch: vi.fn(), setBranchStatus: vi.fn() }))
vi.mock('../../products/api/products', () => ({ listProducts: vi.fn(), createProduct: vi.fn(), updateProduct: vi.fn(), deactivateProduct: vi.fn(), MAX_PRODUCT_TAG_LENGTH: 48, MAX_PRODUCT_TAGS: 20, PRODUCT_IMAGE_MAX_BYTES: 5 * 1024 * 1024, PRODUCT_IMAGE_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp'], normalizeProductTags: (value: unknown) => Array.isArray(value) ? value.map((tag) => String(tag).trim()).filter(Boolean) : [] }))
vi.mock('../../sales/api/sales', () => ({ SALES_CHANNELS: ['pos', 'wholesale', 'event'], recordSale: vi.fn(), getSalesByChannel: vi.fn() }))
const branch = { id: 'branch-1', name: 'Central', status: 'active' as const }
const deferred = <T,>() => {
  let resolve!: (value: T) => void
  const promise = new Promise<T>((done) => { resolve = done })
  return { promise, resolve }
}
const openBranches = async () => {
  fireEvent.click(await screen.findByRole('button', { name: 'Abrir menú de navegación' }))
  fireEvent.click(within(screen.getByRole('dialog', { name: 'Navegación de módulos' })).getByRole('button', { name: /Sucursales/ }))
}
describe('admin branch workspace', () => {
  afterEach(cleanup)
  beforeEach(() => {
    vi.resetAllMocks()
    vi.mocked(authApi.getAdminAccess).mockResolvedValue(true)
    vi.mocked(branchApi.listBranches).mockResolvedValue([])
    vi.mocked(productApi.listProducts).mockResolvedValue([])
    vi.mocked(salesApi.getSalesByChannel).mockResolvedValue([])
    let requestSequence = 0
    vi.stubGlobal('crypto', { randomUUID: vi.fn(() => `request-${++requestSequence}`) })
  })
  it('shows one generic denial and never requests protected data', async () => {
    vi.mocked(authApi.getAdminAccess).mockResolvedValue(false)
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'Acceso no disponible' })).toBeInTheDocument()
    expect(screen.queryByText('inactive')).not.toBeInTheDocument(); expect(branchApi.listBranches).not.toHaveBeenCalled()
  })
  it('focuses an access error and retries the server check', async () => {
    vi.mocked(authApi.getAdminAccess).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(false)
    render(<App />)
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByRole('heading', { name: 'Acceso no disponible' })).toBeInTheDocument()
  })
  it('moves from accessible loading to the empty workspace', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    render(<App />)
    await openBranches()
    expect(await screen.findByText('Cargando sucursales…')).toHaveAttribute('role', 'status')
    load.resolve([])
    expect(await screen.findByText('Aún no hay sucursales.')).toBeInTheDocument()
  })
  it('shows a successful create while an older list is pending', async () => {
    const load = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches).mockReturnValue(load.promise)
    vi.mocked(branchApi.createBranch).mockResolvedValue(branch)
    render(<App />)
    await openBranches()
    await screen.findByText('Cargando sucursales…')
    fireEvent.change(screen.getByLabelText('Nombre de la sucursal'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    expect(await screen.findByText('Central')).toBeInTheDocument()
    expect(screen.queryByText('Cargando sucursales…')).not.toBeInTheDocument()
    load.resolve([])
    await waitFor(() => expect(screen.getByText('Central')).toBeInTheDocument())
  })
  it('serializes commands and keeps the confirmed result visible', async () => {
    const status = deferred<branchApi.Branch>()
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus).mockReturnValue(status.promise)
    render(<App />)
    await openBranches()
    fireEvent.click(await screen.findByRole('button', { name: 'Suspender Central' }))
    for (const name of ['Actualizar sucursales', 'Crear sucursal', 'Suspender Central'])
      expect(screen.getByRole('button', { name })).toBeDisabled()
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    expect(branchApi.createBranch).not.toHaveBeenCalled()
    status.resolve({ ...branch, status: 'suspended' })
    expect(await screen.findByText('Suspendida')).toBeInTheDocument()
  })
  it('keeps the newest admin access response', async () => {
    const older = deferred<boolean>()
    const newer = deferred<boolean>()
    vi.mocked(authApi.getAdminAccess)
      .mockReturnValueOnce(older.promise)
      .mockReturnValueOnce(newer.promise)
    render(<StrictMode><App /></StrictMode>)
    newer.resolve(true)
    await openBranches()
    expect(await screen.findByRole('heading', { name: 'Sucursales' })).toBeInTheDocument()
    older.resolve(false)
    await waitFor(() => expect(screen.queryByRole('heading', { name: 'Acceso no disponible' })).not.toBeInTheDocument())
  })
  it('recovers from a branch loading error', async () => {
    vi.mocked(branchApi.listBranches)
      .mockRejectedValueOnce(new Error('offline'))
      .mockResolvedValueOnce([])
    render(<App />)
    await openBranches()
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveTextContent('No se pudieron cargar las sucursales')
    expect(alert).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByText('Aún no hay sucursales.')).toBeInTheDocument()
  })
  it('retries create with the same request ID', async () => {
    vi.mocked(branchApi.createBranch)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce(branch)
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')
    fireEvent.change(screen.getByLabelText('Nombre de la sucursal'), { target: { value: 'Central' } })
    fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await screen.findByText('No se pudo crear la sucursal.')
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar creación' }))
    expect(await screen.findByText('Central')).toBeInTheDocument()
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).toBe(calls[1][1])
  })
  it('uses a new request ID for a divergent create intent', async () => {
    vi.mocked(branchApi.createBranch).mockRejectedValue(new Error('conflict'))
    render(<App />)
    await openBranches()
    await screen.findByText('Aún no hay sucursales.')
    const input = screen.getByLabelText('Nombre de la sucursal')
    fireEvent.change(input, { target: { value: 'Central' } }); fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await screen.findByText('No se pudo crear la sucursal.')
    fireEvent.change(input, { target: { value: 'North' } }); fireEvent.submit(screen.getByRole('form', { name: 'Crear sucursal' }))
    await waitFor(() => expect(branchApi.createBranch).toHaveBeenCalledTimes(2))
    const calls = vi.mocked(branchApi.createBranch).mock.calls
    expect(calls[0][1]).not.toBe(calls[1][1])
  })
  it('retries a status change with the same request ID', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValue([branch])
    vi.mocked(branchApi.setBranchStatus)
      .mockRejectedValueOnce(new Error('timeout'))
      .mockResolvedValueOnce({ ...branch, status: 'suspended' })
    render(<App />)
    await openBranches()
    fireEvent.click(await screen.findByRole('button', { name: 'Suspender Central' }))
    await screen.findByText('No se pudo cambiar el estado de la sucursal.')
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar cambio de estado' }))
    expect(await screen.findByText('Suspendida')).toBeInTheDocument()
    const calls = vi.mocked(branchApi.setBranchStatus).mock.calls
    expect(calls[0][2]).toBe(calls[1][2])
  })
  it('ignores stale branch responses', async () => {
    vi.mocked(branchApi.listBranches).mockResolvedValueOnce([branch])
    render(<App />)
    await openBranches()
    await screen.findByText('Central')
    const older = deferred<branchApi.Branch[]>()
    const newer = deferred<branchApi.Branch[]>()
    vi.mocked(branchApi.listBranches)
      .mockReturnValueOnce(older.promise)
      .mockReturnValueOnce(newer.promise)
    fireEvent.click(screen.getByRole('button', { name: 'Actualizar sucursales' }))
    fireEvent.click(screen.getByRole('button', { name: 'Actualizar sucursales' }))
    newer.resolve([{ ...branch, id: 'new', name: 'North' }])
    expect(await screen.findByText('North')).toBeInTheDocument()
    older.resolve([{ ...branch, id: 'old', name: 'Stale' }])
    await waitFor(() => expect(screen.queryByText('Stale')).not.toBeInTheDocument())
  })
})
